apiVersion: apps/v1
kind: Deployment
metadata:
  name: complete-devops-deployment
spec:
  selector:
    matchLabels:
      app: complete-devops-app
  template:
    metadata:
      labels:
        app: complete-devops-app
    spec:
      containers:
        - name: complete-devops-app
          image: aecloud/complete-devops-pipeline:1.0.0-21
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
